spring:
  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 2000
      password: foobared
      jedis:
        pool:
          max-active: 100
          max-idle: 10
          max-wait: 100000
  datasource:
      driver-class-name:
      url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: heyang
      druid:
        initial-size: 5 #连接池初始化大小
        min-idle: 10 #最小空闲连接数
        max-active: 20 #最大连接数
        web-stat-filter:
          exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据

        stat-view-servlet: #访问监控网页的登录用户名和密码
          login-username: druid
          login-password: druid
  data:
      elasticsearch:
        repositories:
          enabled: true
        cluster-nodes: 192.168.1.108:9300 # es的连接地址及端口号
        cluster-name: my-application #集群的名称
mybatis:
  mapper-locations: classpath:*/*.xml
redis:
    key:
       prefix:
          authcode: "portal:authcode"
       expire:
            authcode: 120
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头